const PAGE_ENTERED = 'PAGE_ENTERED';
const PAGE_EXITED = 'PAGE_EXITED';
const PAGE_TRANSITION_WITH_TIME = 'PAGE_TRANSITION_WITH_TIME';
const ASSET_VIDEO_METADATA_LOADED = 'ASSET_VIDEO_METADATA_LOADED';
const ASSET_PHOTO_ENDED = 'ASSET_PHOTO_ENDED';
const ASSET_VIDEO_ENDED = 'ASSET_VIDEO_ENDED';
const ASSET_SLIDESHOW_ENDED = 'ASSET_SLIDESHOW_ENDED';
const ASSET_WEB_ENDED = 'ASSET_WEB_ENDED';
const ASSET_TEXT_ENDED = 'ASSET_TEXT_ENDED';

const MOVE_TO_PREV_PAGE = 'MOVE_TO_PREV_PAGE';
const MOVE_TO_NEXT_PAGE = 'MOVE_TO_NEXT_PAGE';
const MOVE_TO_PAGE = 'MOVE_TO_PAGE';
const MOVE_TO_FIRST_PAGE = 'MOVE_TO_FIRST_PAGE';
const MOVE_TO_LAST_PAGE = 'MOVE_TO_LAST_PAGE';
const IFRAME_KEY_DOWN = 'IFRAME_KEY_DOWN';
const IFRAME_HTML_LOADED = 'IFRAME_HTML_LOADED';

export {
  PAGE_ENTERED,
  PAGE_EXITED,
  PAGE_TRANSITION_WITH_TIME,
  ASSET_VIDEO_METADATA_LOADED,
  ASSET_PHOTO_ENDED,
  ASSET_VIDEO_ENDED,
  ASSET_SLIDESHOW_ENDED,
  ASSET_WEB_ENDED,
  ASSET_TEXT_ENDED,

  MOVE_TO_PREV_PAGE,
  MOVE_TO_NEXT_PAGE,
  MOVE_TO_PAGE,
  MOVE_TO_FIRST_PAGE,
  MOVE_TO_LAST_PAGE,

  IFRAME_KEY_DOWN,
  IFRAME_HTML_LOADED
};
